### PR TITLE
KOGITO-1169 : Kogito Quick Starts Update POM

### PR DESCRIPTION
**Pull request by inodeman**
Hi @domhanak , @romartin can you review this short PR? this is needed in order for the Quick Examples to run

### CODE REVIEW

**Comment by romartin** [comment]
@ederign @porcelli how is the owner for this? I cannot assign reviewers neither..

**Comment by radtriste** [comment]
duplicate of https://github.com/kiegroup/kogito-quickstarts/pull/12 ?

**Comment by radtriste** [comment]
@inodeman Can you review all the PRs you created ?
They have different versions change into the main pom.xml but we should keep the SANPSHOT versions IMO

https://github.com/kiegroup/kogito-quickstarts/pull/12 should solve the compilation problems.

**Comment by cristianonicolai** [comment]
@inodeman this needs rebase now

**Comment by radtriste** [comment]
I think this one can be closed or ?
pom.xml has been correclty updated via https://github.com/kiegroup/kogito-quickstarts/pull/12

**Comment by evacchi** [comment]
this is superseded by #12

**Pull request closed without merging**
