### PR TITLE
[Do not Merge] On Hold KOGITO-1189 : Kogito Quick Starts Scripts / User Tasks with Security Update

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin @domhanak can you review this PR?

### CODE REVIEW

**Comment by romartin** [comment]
@ederign @porcelli how is the owner for this? I cannot assign reviewers neither..

**Comment by krisv** [comment]
@inodeman given the security roles metadata does not seem to be present in the updated example (as this is not supported yet in stunner), does the REST junit test that tests unauthorized access still pass?

**Comment by inodeman** [comment]
Hi @krisv you are correct, sorry I should not have sent this one, this one is on hold. Will put note

**Comment by radtriste** [comment]
@inodeman as we merged quickstarts in examples, can you copy this PR on kogito-examples and close this one ?

**Comment by inodeman** [comment]
Hi @radtriste sure thing, I will close, as this one depends on securityRole ticket being worked on I will PR once is done

**Pull request closed without merging**
