### PR TITLE
BAPL-1537 maven-deploy-plugin added to pluginManagement

### PR DESCRIPTION
**Pull request by Ginxo**
BAPL-1537
Without this two maven-deploy-plugin versions 2.7 and 3.0.0-M1 are colliding

### CODE REVIEW

**Review by mswiderski — COMMENTED** [review]
@Ginxo overall it's fine to merge this, especially as short term solution, but might be worth to see if these quickstarts should import kogito bom or use it as parent....

**Comment by Ginxo** [comment]
@mswiderski well this is something you should decide as a team. From my point of view this project should remain as a separate project but as a bom-parent child, but probably I don't have all the information to take a proper decision. So please merge it and if you decide to inherit from bom-parent then this will be removed together with `quarkus.version`, `kogito.version` properties and so on...

**Comment by mareknovotny** [comment]
I think importing kogito-bom in quickstart is expected and wanted, but here is the maven plugin management missing and quickstarts should be standalone in form of build configuration i think and to show the end user recommended usage so inheriting a different parent than quickstart parent here is not good direction to do.

**Comment by mswiderski** [comment]
@mareknovotny so do you want to make any changes or shall this be merged as is?

**Comment by mareknovotny** [comment]
I think this can be merged, but there is more work to polish content, but that can be done later.
I noticed that the convention I proposed in kogito-bom are not used in quickstarts pom.xml files too.

**Comment by Ginxo** [comment]
@mswiderski can you please merge it? thanks

**Review by mswiderski — APPROVED** [review]

**Comment by mswiderski** [comment]
I don't have access to commit to this repo

**Pull request merged**
